### ISSUE TITLE
Documentation - Broken link to Kuesta Overview

### ISSUE THREAD

**Issue by s-hirabaru** [nttcom/kuesta-website#3]
## What happened?
Got 404 error when clicked "Overview of Kuesta" at https://nttcom.github.io/kuesta-website/docs/ .
- en: https://github.com/nttcom/kuesta-website/blob/main/content/en/docs/_index.md?plain=1#L13
- ja: https://github.com/nttcom/kuesta-website/blob/main/content/ja/docs/_index.md?plain=1#L15

## What did you expect to happen?
Transit to the overview page of Kuesta.

## How can we reproduce it (as minimally and precisely as possible)?
1. Access https://nttcom.github.io/kuesta-website/docs/
2. Click "Overview of Kuesta".

**Comment by Tatsuki3939** [comment]
Thank you for your comment.
The OVERVIEW page is currently under construction. (Due to our plans to make major changes to the architecture of Kuesta.)
We apologize for the misunderstanding. We will remove the relevant link at once.
